// <auto-generated />
namespace MoroskoWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changes7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes7));
        
        string IMigrationMetadata.Id
        {
            get { return "201912292245335_changes7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
