//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoroskoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvCPP
    {
        public int Id { get; set; }
        public string projectname { get; set; }
        public string description { get; set; }
        public string studentname { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
