//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoroskoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Finals = new HashSet<Final>();
        }
    
        public int Id { get; set; }
        public string coursename { get; set; }
        public string coursegrade { get; set; }
        //SK: This is here because of the foreign key contraint we have in the finals table.
        //SK: This is a navigation property which holds other enitties related to this entity.
        //SK: The navigation property will hold all the final entities related to this course.
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final> Finals { get; set; }
    }
}
