//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoroskoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final
    {
        public int Id { get; set; }
        public string finalname { get; set; }
        public string finalgrade { get; set; }
        //Foreign key linked to the Id in the course table.
        public int courseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
