//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoroskoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int Id { get; set; }
        public string aspnetusersId { get; set; }
        public int courseId { get; set; }
        public Nullable<int> finalId { get; set; }
        public string coursegrade { get; set; }
        public string finalgrade { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Course Course { get; set; }
        public virtual Final Final { get; set; }
    }
}
