//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoroskoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCours
    {
        public int Id { get; set; }
        public string aspnetusersId { get; set; }
        public int courseId { get; set; }
        public string AspNetUser_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
